name: 'deployment to Tencent Cloud Server'

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo -n "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 101.43.239.215 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: pnpm install
        run: npm i pnpm@latest -g

      - name: build
        run: pnpm install && pnpm run docs:build

      - name: change the folder name
        run:  mv ./docs/.vitepress/dist ./memo28.docs

      - name: Deploy to Tencent Cloud Server
        uses: appleboy/scp-action@master
        with:
         host: ${{ secrets.SERVER_SSH_HOST }} # 服务器域名
         username: ${{ secrets.SERVER_SSH_USER }} # 腾讯云默认用户名为root
         key: ${{ secrets.SERVER_SSH_KEY }} # 本地.ssh文件下的私钥id_rsa，存在secrets中
         source: './memo28.docs' # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
         target: ${{ secrets.SERVER_SSH_TARGET }} # 目标目录
#        run: scp -v -i ~/.ssh/id_rsa -r ./memo28.docs/* root@101.43.239.215:/usr/src
