name: 'deployment to Tencent Cloud Server'

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo -n "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 101.43.239.215 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: pnpm install
        run: npm i pnpm@latest -g

      - name: build
        run: pnpm install && pnpm run docs:build

      - name: change the folder name
        run:  mv ./docs/.vitepress/dist ./memo28.docs


      - name: Deploy to Tencent Cloud Server
        run: scp -v -i ~/.ssh/id_rsa -r ./memo28.docs/* root@101.43.239.215:/usr/src
